export const moduleOptions = [
  { label: 'custom', value: 'custom' },
  { label: 'airline', value: 'airline' },
  { label: 'animal', value: 'animal' },
  { label: 'book', value: 'book' },
  { label: 'color', value: 'color' },
  { label: 'commerce', value: 'commerce' },
  { label: 'company', value: 'company' },
  { label: 'database', value: 'database' },
  { label: 'date', value: 'date' },
  { label: 'finance', value: 'finance' },
  { label: 'food', value: 'food' },
  { label: 'image', value: 'image' },
  { label: 'internet', value: 'internet' },
  { label: 'location', value: 'location' },
  { label: 'lorem', value: 'lorem' },
  { label: 'music', value: 'music' },
  { label: 'number', value: 'number' },
  { label: 'person', value: 'person' },
  { label: 'phone', value: 'phone' },
  { label: 'science', value: 'science' },
  { label: 'string', value: 'string' },
  { label: 'vehicle', value: 'vehicle' },
  { label: 'word', value: 'word' },
];
