export const subModuleOptions = {
  airline: [
    { label: 'aircraftType', value: 'aircraftType' },
    { label: 'airline', value: 'airline' },
    { label: 'airplane', value: 'airplane' },
    { label: 'airport', value: 'airport' },
    { label: 'flightNumber', value: 'flightNumber' },
    { label: 'recordLocator', value: 'recordLocator' },
    { label: 'seat', value: 'seat' },
  ],
  animal: [
    { label: 'bear', value: 'bear' },
    { label: 'bird', value: 'bird' },
    { label: 'cat', value: 'cat' },
    { label: 'cetacean', value: 'cetacean' },
    { label: 'cow', value: 'cow' },
    { label: 'crocodilia', value: 'crocodilia' },
    { label: 'dog', value: 'dog' },
    { label: 'fish', value: 'fish' },
    { label: 'horse', value: 'horse' },
    { label: 'insect', value: 'insect' },
    { label: 'lion', value: 'lion' },
    { label: 'petName', value: 'petName' },
    { label: 'rabbit', value: 'rabbit' },
    { label: 'rodent', value: 'rodent' },
    { label: 'snake', value: 'snake' },
    { label: 'type', value: 'type' },
  ],
  book: [
    { label: 'author', value: 'author' },
    { label: 'format', value: 'format' },
    { label: 'genre', value: 'genre' },
    { label: 'publisher', value: 'publisher' },
    { label: 'series', value: 'series' },
    { label: 'title', value: 'title' },
  ],
  color: [
    { label: 'cmyk', value: 'cmyk' },
    { label: 'colorByCSSColorSpace', value: 'colorByCSSColorSpace' },
    { label: 'cssSupportedFunction', value: 'cssSupportedFunction' },
    { label: 'cssSupportedSpace', value: 'cssSupportedSpace' },
    { label: 'hsl', value: 'hsl' },
    { label: 'human', value: 'human' },
    { label: 'hwb', value: 'hwb' },
    { label: 'lab', value: 'lab' },
    { label: 'lch', value: 'lch' },
    { label: 'rgb', value: 'rgb' },
    { label: 'space', value: 'space' },
  ],
  commerce: [
    { label: 'department', value: 'department' },
    { label: 'isbn', value: 'isbn' },
    { label: 'price', value: 'price' },
    { label: 'product', value: 'product' },
    { label: 'productAdjective', value: 'productAdjective' },
    { label: 'productDescription', value: 'productDescription' },
    { label: 'productMaterial', value: 'productMaterial' },
    { label: 'productName', value: 'productName' },
  ],
  company: [
    { label: 'buzzAdjective', value: 'buzzAdjective' },
    { label: 'buzzNoun', value: 'buzzNoun' },
    { label: 'buzzPhrase', value: 'buzzPhrase' },
    { label: 'buzzVerb', value: 'buzzVerb' },
    { label: 'catchPhrase', value: 'catchPhrase' },
    { label: 'catchPhraseAdjective', value: 'catchPhraseAdjective' },
    { label: 'catchPhraseDescriptor', value: 'catchPhraseDescriptor' },
    { label: 'catchPhraseNoun', value: 'catchPhraseNoun' },
    { label: 'name', value: 'name' },
  ],
  database: [
    { label: 'collation', value: 'collation' },
    { label: 'column', value: 'column' },
    { label: 'engine', value: 'engine' },
    { label: 'mongodbObjectId', value: 'mongodbObjectId' },
    { label: 'type', value: 'type' },
  ],
  date: [
    { label: 'anytime', value: 'anytime' },
    { label: 'between', value: 'between' },
    { label: 'betweens', value: 'betweens' },
    { label: 'birthdate', value: 'birthdate' },
    { label: 'future', value: 'future' },
    { label: 'month', value: 'month' },
    { label: 'past', value: 'past' },
    { label: 'recent', value: 'recent' },
    { label: 'soon', value: 'soon' },
    { label: 'timeZone', value: 'timeZone' },
    { label: 'weekday', value: 'weekday' },
  ],
  finance: [
    { label: 'accountName', value: 'accountName' },
    { label: 'accountNumber', value: 'accountNumber' },
    { label: 'amount', value: 'amount' },
    { label: 'bic', value: 'bic' },
    { label: 'bitcoinAddress', value: 'bitcoinAddress' },
    { label: 'creditCardCVV', value: 'creditCardCVV' },
    { label: 'creditCardIssuer', value: 'creditCardIssuer' },
    { label: 'creditCardNumber', value: 'creditCardNumber' },
    { label: 'currency', value: 'currency' },
    { label: 'currencyCode', value: 'currencyCode' },
    { label: 'currencyName', value: 'currencyName' },
    { label: 'currencySymbol', value: 'currencySymbol' },
    { label: 'ethereumAddress', value: 'ethereumAddress' },
    { label: 'iban', value: 'iban' },
    { label: 'litecoinAddress', value: 'litecoinAddress' },
    { label: 'maskedNumber', value: 'maskedNumber' },
    { label: 'pin', value: 'pin' },
    { label: 'routingNumber', value: 'routingNumber' },
    {
      label: 'transactionDescription',
      value: 'transactionDescription',
    },
    { label: 'transactionType', value: 'transactionType' },
  ],
  food: [
    { label: 'adjective', value: 'adjective' },
    { label: 'description', value: 'description' },
    { label: 'dish', value: 'dish' },
    { label: 'ethnicCategory', value: 'ethnicCategory' },
    { label: 'fruit', value: 'fruit' },
    { label: 'ingredient', value: 'ingredient' },
    { label: 'meat', value: 'meat' },
    { label: 'spice', value: 'spice' },
    { label: 'vegetable', value: 'vegetable' },
  ],
  image: [
    { label: 'avatar', value: 'avatar' },
    { label: 'avatarGitHub', value: 'avatarGitHub' },
    { label: 'dataUri', value: 'dataUri' },
    { label: 'url', value: 'url' },
    { label: 'urlLoremFlickr', value: 'urlLoremFlickr' },
    { label: 'urlPicsumPhotos', value: 'urlPicsumPhotos' },
    { label: 'urlPlaceholder', value: 'urlPlaceholder' },
  ],
  internet: [
    { label: 'color', value: 'color' },
    { label: 'displayName', value: 'displayName' },
    { label: 'domainName', value: 'domainName' },
    { label: 'domainSuffix', value: 'domainSuffix' },
    { label: 'domainWord', value: 'domainWord' },
    { label: 'email', value: 'email' },
    { label: 'emoji', value: 'emoji' },
    { label: 'exampleEmail', value: 'exampleEmail' },
    { label: 'httpMethod', value: 'httpMethod' },
    { label: 'httpStatusCode', value: 'httpStatusCode' },
    { label: 'ip', value: 'ip' },
    { label: 'ipv4', value: 'ipv4' },
    { label: 'ipv6', value: 'ipv6' },
    { label: 'jwt', value: 'jwt' },
    { label: 'jwtAlgorithm', value: 'jwtAlgorithm' },
    { label: 'mac', value: 'mac' },
    { label: 'password', value: 'password' },
    { label: 'port', value: 'port' },
    { label: 'protocol', value: 'protocol' },
    { label: 'url', value: 'url' },
    { label: 'userAgent', value: 'userAgent' },
    { label: 'username', value: 'username' },
  ],
  location: [
    { label: 'buildingNumber', value: 'buildingNumber' },
    { label: 'cardinalDirection', value: 'cardinalDirection' },
    { label: 'city', value: 'city' },
    { label: 'continent', value: 'continent' },
    { label: 'country', value: 'country' },
    { label: 'countryCode', value: 'countryCode' },
    { label: 'direction', value: 'direction' },
    { label: 'latitude', value: 'latitude' },
    { label: 'longitude', value: 'longitude' },
    { label: 'nearbyGPSCoordinate', value: 'nearbyGPSCoordinate' },
    { label: 'ordinalDirection', value: 'ordinalDirection' },
    { label: 'secondaryAddress', value: 'secondaryAddress' },
    { label: 'state', value: 'state' },
    { label: 'street', value: 'street' },
    { label: 'streetAddress', value: 'streetAddress' },
    { label: 'timeZone', value: 'timeZone' },
    { label: 'zipCode', value: 'zipCode' },
  ],
  lorem: [
    { label: 'lines', value: 'lines' },
    { label: 'paragraph', value: 'paragraph' },
    { label: 'paragraphs', value: 'paragraphs' },
    { label: 'sentence', value: 'sentence' },
    { label: 'sentences', value: 'sentences' },
    { label: 'slug', value: 'slug' },
    { label: 'text', value: 'text' },
    { label: 'word', value: 'word' },
    { label: 'words', value: 'words' },
  ],
  music: [
    { label: 'album', value: 'album' },
    { label: 'artist', value: 'artist' },
    { label: 'genre', value: 'genre' },
    { label: 'songName', value: 'songName' },
  ],
  number: [
    { label: 'bigInt', value: 'bigInt' },
    { label: 'binary', value: 'binary' },
    { label: 'float', value: 'float' },
    { label: 'hex', value: 'hex' },
    { label: 'int', value: 'int' },
    { label: 'octal', value: 'octal' },
    { label: 'romanNumeral', value: 'romanNumeral' },
  ],
  person: [
    { label: 'bio', value: 'bio' },
    { label: 'firstName', value: 'firstName' },
    { label: 'fullName', value: 'fullName' },
    { label: 'jobArea', value: 'jobArea' },
    { label: 'jobDescriptor', value: 'jobDescriptor' },
    { label: 'jobTitle', value: 'jobTitle' },
    { label: 'jobType', value: 'jobType' },
    { label: 'lastName', value: 'lastName' },
    { label: 'middleName', value: 'middleName' },
    { label: 'sex', value: 'sex' },
    { label: 'prefix', value: 'prefix' },
    { label: 'suffix', value: 'suffix' },
    { label: 'zodiacSign', value: 'zodiacSign' },
  ],
  phone: [
    { label: 'imei', value: 'imei' },
    { label: 'number', value: 'number' },
  ],
  science: [
    { label: 'chemicalElement', value: 'chemicalElement' },
    { label: 'unit', value: 'unit' },
  ],
  string: [
    { label: 'alpha', value: 'alpha' },
    { label: 'alphanumeric', value: 'alphanumeric' },
    { label: 'binary', value: 'binary' },
    { label: 'fromCharacters', value: 'fromCharacters' },
    { label: 'hexadecimal', value: 'hexadecimal' },
    { label: 'nanoid', value: 'nanoid' },
    { label: 'numeric', value: 'numeric' },
    { label: 'octal', value: 'octal' },
    { label: 'symbol', value: 'symbol' },
    { label: 'ulid', value: 'ulid' },
    { label: 'uuid', value: 'uuid' },
  ],
  vehicle: [
    { label: 'bicycle', value: 'bicycle' },
    { label: 'color', value: 'color' },
    { label: 'fuel', value: 'fuel' },
    { label: 'manufacturer', value: 'manufacturer' },
    { label: 'model', value: 'model' },
    { label: 'type', value: 'type' },
    { label: 'vehicle', value: 'vehicle' },
    { label: 'vin', value: 'vin' },
    { label: 'vrm', value: 'vrm' },
  ],
  word: [
    { label: 'adjective', value: 'adjective' },
    { label: 'adverb', value: 'adverb' },
    { label: 'conjunction', value: 'conjunction' },
    { label: 'interjection', value: 'interjection' },
    { label: 'noun', value: 'noun' },
    { label: 'preposition', value: 'preposition' },
    { label: 'verb', value: 'verb' },
    { label: 'words', value: 'words' },
  ],
};
